### ISSUE TITLE
ChatEngine.me.notifications is undefined after setup

### ISSUE THREAD

**Issue by alyssawolejko** [pubnub/chat-engine-push-notifications#6]
Am I setting this up incorrectly?
I have a Root.js component that initializes the ChatEngine and sets up the plugins.
I see the protoPlugins in the ChatEngine object but `ChatEngine.me.notifications` is undefined. I've had issues with putting the `chat-engine-push-notifications` plugin initialization anywhere but the `ChatEngine.on('$.ready')` function (noted in commented out code below). 

**Root.js:** 
```
import React, { Component } from 'react';
import ChatEngineCore from 'chat-engine';
import { plugin } from 'chat-engine-notifications';
import typingIndicator from "chat-engine-typing-indicator";

const ChatEngine = ChatEngineCore.create(
  { 
    publishKey: PUBNUB_PUBLISH_KEY, 
    subscribeKey: PUBNUB_SUBSCRIBE_KEY
  },
  { 
    debug: true
  }
);
/**
** PUTTING THIS HERE WILL CAUSE ChatEngine.on($.ready) event TO NOT FIRE
** ChatEngine.proto('Me', plugin({
** events: ['$.invite', 'message'],
** platforms: { ios: true, android: true }
** }))
** I get the below Callback Warning in the console when the above is uncommented
**/

export default class Root extends Component { 
  state =  { loading: true } 

  componentDidMount() {
    console.disableYellowBox = true    
    this.props.setChatEngine(ChatEngine) // stores ref with Redux
    ChatEngine.on('$.ready', this.onChatEngineReady)    
  }
  componentWillReceiveProps(nextProps) {
    if (this.props.user !== nextProps.user){
      let { user, user: { patient_fields: { pubnub_authkey } } } = nextProps
      // connect the user to pubnub when available from Redux store
      if (user){
        ChatEngine.connect(`patient.${user.id}`, {
          signedOnTime: Date.now()
        }, pubnub_authkey)
      }
    }
  }
  onChatEngineReady = () => {
    ChatEngine.proto('Me', plugin({
      events: ['$.invite', 'message'],
      platforms: { ios: true, android: true }
    }))
    ChatEngine.proto('Chat', typingIndicator({ timeout: 3000 }));
    console.log(ChatEngine)
    // ChatEngine.me.notifications.on('$.notifications.received', this.onNotification);
    // ChatEngine.me.notifications.registerNotificationActions({ Accept: 'default', Reject: 'none' });
    // ChatEngine.me.notifications.registerNotificationChannels([
    //     { id: 'cennotifications', name: 'CENNotifications Channel' }
    // ])
    // ChatEngine.me.notifications.requestPermissions({alert: true, badge: false, sound: true})
    //   .then(permissions => console.log('Granted with permissions:', JSON.stringify(permissions)))
    //   .catch(error => console.log('Permissions request did fail:', error))
  }

}
```
**ChatEngine Debug Console:** 

![screen shot 2018-07-11 at 9 49 28 am](https://user-images.githubusercontent.com/8005760/42576315-114d4dd6-84f0-11e8-8d4c-f4a6f056da91.png)

![screen shot 2018-07-11 at 9 50 03 am](https://user-images.githubusercontent.com/8005760/42576314-11322c90-84f0-11e8-9901-7554d73eea5d.png)

**Callback Warning:**
<img width="839" alt="screen shot 2018-07-10 at 4 02 53 pm" src="https://user-images.githubusercontent.com/8005760/42576761-1fdad62e-84f1-11e8-8794-3beeac768041.png">

**Comment by parfeon** [comment]
@alyssawolejko we pushed ChatEngine SDK update with fixes for `react-native` (looks like react-native is buggy again and require some special changes for it).

**Comment by parfeon** [comment]
@alyssawolejko after node modules will be updated, you can uncomment code in **Root.js**.
Proto plugins should be initialized as soon as possible - better after ChatEngine instantiation/configuration.

**Comment by alyssawolejko** [comment]
Hi @parfeon I updated the dependencies but still have the same issues. Here are my dependencies: 
```
  "dependencies": {
    "axios": "^0.18.0",
    "chat-engine": "^0.9.18",
    "chat-engine-gravatar": "^0.0.8",
    "chat-engine-notifications": "^1.0.11",
    "chat-engine-typing-indicator": "^0.0.9",
    "moment": "^2.22.2",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-camera-roll-picker": "^1.2.3",
    "react-native-device-info": "^0.21.5",
    "react-native-elements": "^0.19.1",
    "react-native-exception-handler": "^2.8.9",
    "react-native-htmlview": "^0.12.1",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.2.5",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0"
  }
```

**Comment by parfeon** [comment]
@alyssawolejko I've checked how it works using version of `chat-engine` from **0.9.16** up to **0.9.18** and there was no troubles anymore (at start, before fix I was able to catch some errors).

Can you try to reset caches of `react-native` deployment server by calling this: 
```
npm start -- --reset-cache
```

If it doesn't work, can you try on different machine (which doesn't have anything cached for project).
If issue still be there, will it be possible to share smallest version of project, which is able to reproduce issue?

**Comment by alyssawolejko** [comment]
@parfeon I was able to reproduce on another machine as well as in a clean project. Here is a link to a repo that is a new ejected create-react-native-app instance with the minimum ChatEngine code: https://github.com/alyssawolejko/pubnub-chat-engine-sample

**Comment by parfeon** [comment]
@alyssawolejko thanks for example.

Is it close to your application? I'm asking, because this plugin utilize both sides which bridged by `react-native` and require integration on iOS side as well.
In shared example it crash, because it try to communicate with other half (which is running on iOS side) and unable to reach it.

Please, check integration docs into native application [here](https://github.com/pubnub/chat-engine-push-notifications/wiki/integration#integration-into-ios-application).

**Comment by parfeon** [comment]
@alyssawolejko link above have following:  
1. `Podfile` configuration on step **# 1** to add ReactNative counterpart of this plugin and how to install dependencies on step **# 2**.
2. Addition of plugin headers shown in [this](https://github.com/pubnub/chat-engine-push-notifications/wiki/integration#chat-demo) section on step **# 3** 
3. iOS counterpart of plugin can work only using Application delegate callbacks which all listed in [this](https://github.com/pubnub/chat-engine-push-notifications/wiki/integration#chat-demo) section on step **# 4** (sorry for Swift example, but Objective-C has common syntax).
4. ReactNative application load shown in [this](https://github.com/pubnub/chat-engine-push-notifications/wiki/integration#chat-demo) section on step **# 5**.

Because you used `create-react-native-app`, you probably won't need all libraries from **# 1** from list above and `Podfile` can be as simple as this:  
```ruby
platform :ios, '10.0'

target '<XcodeTargetName>' do
    pod 'CENNotifications', :path => '../node_modules/chat-engine-notifications'
end
```  
`Podfile` should be located inside of **ios** directory. Make sure to replace `<XcodeTargetName>` with actual name of target in your Xcode project.  

Also **# 4** also not required, since this code should be added by  `create-react-native-app` by template project which it use.


Actually there is demo project inside of this repository: https://github.com/pubnub/chat-engine-push-notifications/tree/master/demo. One issue with ReactNative is what it get confused by upper directories, so when you checkout repository, make sure to move **demo** folder elsewhere outside of directory which contain repository code (ReactNative try to use babel configuration files while compiling sources).

**Comment by alyssawolejko** [comment]
@parfeon is there a solution that doesn't involve CocoaPods?  I prefer not to use them in projects because of how they play with other packages.

**Comment by dtaborda** [comment]
@parfeon I'm having the same issue of @alyssawolejko, `ChatEngine.me.notifications` is `undefined` and my javascript's code is similar of her and I had the same issue

Can you explain step by step how did you configured the push notification into your environment ?

**Comment by parfeon** [comment]
@alyssawolejko sorry what it took so long to response.

You can do it w/o CocoaPods, but not as fancy as it is done with ReactNative own libraries:  
1. Open your Xcode project and find some place, where `CENNotifications` source code folder will be placed.
2. Navigate in your project to: `node_modules/chat-engine-notifications/Libraries/ios`
3. _Drag&Drop_ `CENNotifications` folder into Xcode project.
4. Instead of `<CENNotifications/CENNotifications.h>` import just `CENNotifications.h`, since code is not part of framework, but will be part of project.

iOS UIApplicationDelegate methods usage required, to make library work properly. W/o that code, `ChatEngine` won't enable push notifications on chats.

**Comment by alyssawolejko** [comment]
@parfeon I was able to piece a solution together, i will work on documenting my solution and post here. In the meantime, how do you go about testing these push notifications (from the PubNub console)?

I'm currently not receiving push notifications for messages. I have both Development & Distribution APNS certs in PubNub, currently working off of the Development auth / subscribe keys. 

Am I missing any iOS UIApplicationDelegate methods from the functions I posted above `AppDelegate.swift` ? These were right from the PubNub docs (https://github.com/pubnub/chat-engine-push-notifications/wiki/integration#chat-demo)

**Comment by parfeon** [comment]
@alyssawolejko Web-console won't show any information, because message which has been tested should include `pn_debug` flag inside (ChatEngine doesn't add this to the root of object).

I've just tested with demo application from this repository and push notifications still working. I've connected user and created new chat. 
From web-console, I've subscribed to channel which represent this chat. Here is channel [names topology](https://www.pubnub.com/docs/chat-engine/pubnub-channel-topology#globalChannel-and-chat-public) which is used by ChatEngine - this make possible to predict name of channel to which subscribe in web-console.

From device I've sent message and took whole payload from web console. It was something like this (if plugin integrated properly): 
```
{
  "data": { 
    "text": "Hello there" 
  }, 
  "sender": "moon", 
  "event": "message", 
  "chatengineSDK": "0.9.18", 
  "pn_apns": { 
    "aps": { 
      "alert": { 
        "title": "moon send message in test", 
        "body": "Hello there"
      }, 
      "category": "com.pubnub.chat-engine.message"
    }, 
    "cepayload": { 
      "sender": "moon", 
      "chat": "chat-engine#chat#public.#test", 
      "event": "message", 
      "data": { 
        "text": "Hello there" 
      }, 
      "ceid": "3812ab19-f30b-4400-a1cb-0ec7cb2a7fcc", 
      "category": "com.pubnub.chat-engine.message" 
    } 
  }, 
  "pn_gcm": { 
    "data": { 
      "contentTitle": "moon send message in test", 
      "contentText": "Hello there", 
      "ticker": "New chat message", 
      "cepayload": { 
        "sender": "moon", 
        "chat": "chat-engine#chat#public.#test", 
        "event": "message", 
        "data": { 
          "text": "Hello there" 
        }, 
        "ceid": "3812ab19-f30b-4400-a1cb-0ec7cb2a7fcc", 
        "category": "com.pubnub.chat-engine.message" 
      } 
    } 
  } 
}
```

Then I've closed application and used received message payload to publish it from web-console - push notification appeared in Notification Center.

It is known information for developers under Apple products, what to enable push notifications, it is also required to:  
1. Specify bundle identifier for your application - it should be same, as in Apple's dev portal for which push notification certificates has been created and provisioning profile created:  
    <img width="532" alt="screen shot 2018-07-26 at 22 48 12" src="https://user-images.githubusercontent.com/794617/43284947-1df5060e-9126-11e8-81b9-e28335d81bbf.png">
2. Ensure, what push notification feature enabled in `Capabilities`:  
    <img width="702" alt="screen shot 2018-07-26 at 22 50 11" src="https://user-images.githubusercontent.com/794617/43284990-471d6666-9126-11e8-8d36-e2db4a38212c.png">

If there is issues with step **1** then I suggest to read documentation about how to create all certificates and complete project configuration from [here](https://www.pubnub.com/docs/ios-objective-c/mobile-gateway#apns-prerequisites-certs)

**Comment by franklinyang** [comment]
Hi Sergey -- thank you for all of your help over the past few weeks. I'm a member of Alyssa's team, also working on push notifications.

We're almost there!

I am trying to attach a notification payload to our pubnub messages being sent from a **web-based** (not react-native) app with ChatEngine. For web, should I be using the formatter in https://github.com/pubnub/chat-engine-push-notifications/blob/master/demo/src/helpers/formatter.js?

Secondly, I am a little confused about the usage here... the `pn_gcm` data element in your previous example is at the top-level of the pubnub payload. However, the only method I see in the documentation to send a message is `emit`, which takes in `data` parameter and makes everything a child of the `data` parameter.

Here is the data payload in the message we emit from our web app. As you can see, the `pn_gcm` payload is incorrectly under the data object.
![image](https://user-images.githubusercontent.com/1901335/43422086-ae707450-9416-11e8-947d-e1058897ba2d.png)

**Comment by parfeon** [comment]
@franklinyang sorry for late response, just needed some time to gather information for response.

Indeed, there is no formatter for web-based client nor NodeJS.  
Mentioned `formatter.js` from your response just create APNS/GCM payloads, which with plugin will be merged with actual payload which will be emitted.  
You can see code from `normalize` function [here](https://github.com/pubnub/chat-engine-push-notifications/blob/master/src/helpers/formatter.js#L154-L201) which wrap everything. In that function, it rebuild whole event payload with new data in it.
So, for your case it is better to check code from library's formatter and normalizer (not demo application).

To make any changes into emitted event, we need to create [middleware](https://www.pubnub.com/docs/chat-engine/build-a-plugin#middleware) which will be registered as `proto` plugin for `'Chat'` (just to make sure we won't miss emit events).  

Here is simple middleware which you can customize for your needs:   

```js
// web-push-formatter-middleware.js
module.exports = (config) => {
    return {
        middleware: {
            emit:
                message: (payload, next) => {
                    payload.pn_apns = {
                        aps: { 
                            alert: { 
                                body: "Test message", 
                                title: "New message from Firefly Health" 
                            } 
                        }
                    };

                    next(err, payload);
                }
            }
        }
    };
}
```

In example above:  
* `message` - is name of emitted event. It can be any string which you place as first argument of `emit`. 
* `payload.chat` - contains reference on [Chat](https://www.pubnub.com/docs/chat-engine/reference/chat) instance. 
* `payload.sender` - contains reference on [Me](https://www.pubnub.com/docs/chat-engine/reference/me) instance.

When you will create your middleware, please take a not on keys and values from [this](#issuecomment-408215289) response.  JS version of ChatEngine doesn't include events identifiers on it's own (Objective-C version went ahead of time here and add it to event payload) which may be changed in future.

As a note, there will be update in which `ceid` will be replaced with `eid` in react-native push notification plugin.

**Comment by parfeon** [comment]
@franklinyang `next` callback accept two arguments: error and modified payload.

Probably it was my error just copy&paste some pieces. In your application `next(null, payload);` should be used.

**Comment by franklinyang** [comment]
@parfeon Thanks, I've verified that we're able to monkey-patch the message correctly.

Now we're running into another problem. When we register our APNS token with Pubnub and try to send a message and trigger a push notification, I get this error in the debug console:
```
"Invalid APNS token: 3ae81b9d38a50eef826d4cb5942937d2eb282971c352c16fe50220f8bca686ce"
```

I printed out the APNS token returned from pubnub in the `ChatEngine.me.notifications.on('$.notifications.registered', [...]` event, and the token being returned is capitalized. In the example above, the token is actually `3AE81B...`

----------
Additional details:
- Code for middleware:
 3 export const WebPushFormatterPlugin = () => {
  4   return {
  5     middleware: {
  6       emit: {
  7         message: (payload, next) => {
  8           payload.pn_apns = {
  9             aps: {
 10               alert: {
 11                 body: "Test message",
 12                 title: "New message from Firefly Health"
 13               },
 14               category: "com.pubnub.chat-engine.message"
 15             },
 16           };
 17           payload.pn_debug = true
 18           next(null, payload);
 19         }
 20       }
 21     }
 22   }
 23 };
- Code for registering APNS token (was working before)
```
146     // triggers when a phone receives a PN
147     ChatEngine.me.notifications.on(
148       '$.notifications.received',
149       this.onNotification
150     );
151     // register user options for alert
152     ChatEngine.me.notifications.registerNotificationActions({
153       Accept: 'default',
154       Reject: 'none',
155     });
156     // create a custom channel for the PN to be routed to
157     ChatEngine.me.notifications.registerNotificationChannels([
158       { id: 'cennotifications', name: 'CENNotifications Channel' },
159     ]);
160     // triggers alert for user to Allow or Decline PNs
161     ChatEngine.me.notifications.requestPermissions(
162       { alert: true, badge: false, sound: true },
163       [new CENInvitationNotificationCategory()]
164     );
165     // .then(permissions => console.log('Granted with permissions:', JSON.stringify(permissions)))
166     // .catch(error => console.log('Permissions request did fail:', error))
167
168     /*
169     ** Triggers when the user has ALLOWED PNs
170     ** update the user object's device_token
171     */
172     ChatEngine.me.notifications.on('$.notifications.registered', (token) => {
173       updateUser(user.id, {
174         patient_fields: {
175           device_token: token,
176         },
177       });
178     });
179
180     // triggers when the user has REJECTED PNs
181     ChatEngine.me.notifications.on(
182       '$.notifications.registration.fail',
183       (error) => {
184         console.log('Device registration did fail:', error);
185       }
186     );
187   };
188
```

**Comment by parfeon** [comment]
@franklinyang Trying to find out from OPs, why it happens for valid device token.

**Comment by franklinyang** [comment]
Thanks Sergey - what is OPs? Also, is it possible that Pubnub is lowercasing my APNS key after it is registered?

The APNS key I uploaded was capitalized: `3AE81B...`, whereas the APNS token returned from pubnub is lowercased: `"Invalid APNS token: 3ae81b..."`

**Comment by parfeon** [comment]
@franklinyang it was for servers engineers.

There is nothing wrong with lowercasing, because not much services case about it when processing received data (especially if sent with GET request).

`The APNS key I uploaded was capitalized` - is it about log message in function, which get notified when iOS was able to register for push notifications and received token?

```
"Invalid APNS token: 3ae81b9d38a50eef826d4cb5942937d2eb282971c352c16fe50220f8bca686ce"
```

This message has been forwarded from APNS service itself (feedback service). So, here is what happened:  
1. device, using configured provisioning profile (usually defined and managed by `application bundle identifier`) ask APNS to provide device push token (this token is bound to APNS certificate which has been created in linkage to provisioning profile - application on Apple's developer portal)
2. after device push token has been received (`3ae81b9d38a50eef826d4cb5942937d2eb282971c352c16fe50220f8bca686ce`), it is used by underlying PubNub client to register chats for push notifications - at this moment, it is just mapping in database table w/o actual calls to APNS
3. event emitted with `pn_apns` in it (emitted event is actually message which is published with underlying PubNub client)
4. message reach PubNub service and it send it further through real-time network
5. service detects `pn_apns` field in message payload and use it's content to place it into push notification queue (to be sent)
6. as described in Apple's docs about notification providers, they open connection using available push notification certificate and compose messages using device tokens (those, which has been passed to PubNub service at **second** step).
7. after all payloads ready, service send them to APNS which deliver them.
8. (optional) if something is wrong, Apple's feedback service return error information and PubNub server removes broken token from database.

From all this, I can see only one reason of failure: environment configuration conflict.  
It looks like different certificates has been mixed up: ChatEngine has been initialized with keys, where has been uploaded certificate for different bundle identifier or production / development environment, then used in iOS application.   
So, application request and receive device push token under one certificate, but PubNub has been instructed to use different one (this defined by set of used keys in ChatEngine) and as result, Apple unable to find device push token for certificate used by notification provider and discard it (report invalid token).

**Comment by martinvol** [comment]
Hello @parfeon

I followed the instructions you gave here: https://github.com/pubnub/chat-engine-push-notifications/issues/6#issuecomment-407649369

And I can't get xcode to finde the library, I am placing the code in the right place?

Here I attach an how my tree looks like and the error:

![image](https://user-images.githubusercontent.com/698027/43691230-bda1c73e-98ef-11e8-86bd-b7d68be237ac.png)

Best!

**Comment by martinvol** [comment]
And also @parfeon, 

if you notice my project I don't have a AppDelegate `AppDelegate.swift` file, I just have a `AppDelegate.m`. What should I put there code?

**Comment by parfeon** [comment]
@martinvol **.m** - is really good choice in (it is for Objective-C).

From screenshot it looks like, folder with sources has been added as `folder reference` - in this case compiler doesn't work well. Remove `CENNotifications` folder from Xcode project tree and drag it again from `node_modules/chat-engine-notifications/Libraries/ios`, but make sure to select `Create groups` in shown interface. Also, don't forget to set checkboxes on targets for which it should be compiled.

From screenshot I can't tell for sure, but it is worth to note, what this library works only as part of ReactNative environment.

**Comment by franklinyang** [comment]
Hi Sergey -

You were 100% right -- this was an environment issue. Thank you for responding so quickly these past few weeks. Your help has been immensely helpful.

**Comment by martinvol** [comment]
Thanks for the quick answer @parfeon .

I'm not sure I understand that you mean, I only have a `.m` file in my projec, I started it with `create-react-native-app ...`.

So I just went ahead and copied @alyssawolejko's `AppDelegate.swif` and deleted the `AppDelegate.m`, `AppDelegate.h` and `main.m` files.

I'm still getting this error:

![image](https://user-images.githubusercontent.com/698027/43739318-06c30654-999e-11e8-908a-63f7d3484696.png)

and if I add the `@available(iOS 10.0, *)` at the top of the class like xcode suggests, I get this error:

![image](https://user-images.githubusercontent.com/698027/43739400-42d7c102-999e-11e8-883c-16616b4e83f6.png)


Can you give me a `AppDelegate.swif` I could copy or a working demo project? There's no `AppDelegate.swif` file in the demo in this repo and I really don't understand why.

Thanks

**Comment by parfeon** [comment]
@martinvol it doesn't work that way. Your project has been created as normal Objective-C project (if there is no `.swift` files in it).

It is not required to use Swift (it is just trendy stuff) and if `create-react-native-app` created Objective-C project, you can keep using it.

I can't give you Swift file, because the one created by `create-react-native-app` for @alyssawolejko. 
Here 
https://github.com/pubnub/chat-engine-push-notifications/issues/6#issuecomment-406382363 I responded, what this repository itself has demo project which shows plugin integration, but I wrote it with Objective-C.

**Comment by alyssawolejko** [comment]
@martinvol Here is my `AppDelegate.swift` and `Bridging-Header.h`. I had to add CENNotifications under Xcodes Framework Search paths and Header Search Paths to get this to work : 

**CENNotifications directory at app/ios**
<img width="270" alt="screen shot 2018-08-06 at 6 33 05 pm" src="https://user-images.githubusercontent.com/8005760/43744250-2efa036c-99a7-11e8-9e46-a0014df80e39.png">



**AppDelegate.swift**
```
//
//  AppDelegate.swift
//  FireflyHealth
//
//  Created by Alyssa Wolejko on 7/19/18.
//  Copyright © 2018 Facebook. All rights reserved.
//

import Foundation

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
  var window: UIWindow?
  var bridge: RCTBridge!
  
  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    let jsCodeLocation: URL
    
    jsCodeLocation = RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index", fallbackResource:nil)
    let rootView = RCTRootView(bundleURL: jsCodeLocation, moduleName: "FireflyHealth", initialProperties: nil, launchOptions: launchOptions)
    let rootViewController = UIViewController()
    rootViewController.view = rootView
    
    self.window = UIWindow(frame: UIScreen.main.bounds)
    self.window?.rootViewController = rootViewController
    self.window?.makeKeyAndVisible()
    
    CENNotifications.application(application, didFinishLaunchingWithOptions: launchOptions)

    return true
  }
  
  
  func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    CENNotifications.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
  }
  
  func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
    CENNotifications.application(application, didFailToRegisterForRemoteNotificationsWithError: error)
  }
  
  func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any],
                   fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
    CENNotifications.application(application, didReceiveRemoteNotification: userInfo,
                                 fetchCompletionHandler: completionHandler)
  }
  
  func application(_ application: UIApplication, handleActionWithIdentifier identifier: String?,
                   forRemoteNotification userInfo: [AnyHashable : Any], completionHandler: @escaping () -> Void) {
    CENNotifications.application(application, handleActionWithIdentifier: identifier, forRemoteNotification: userInfo,
                                 completionHandler: completionHandler)
  }
  
  func application(_ application: UIApplication, handleActionWithIdentifier identifier: String?,
                   forRemoteNotification userInfo: [AnyHashable : Any],
                   withResponseInfo responseInfo: [AnyHashable : Any], completionHandler: @escaping () -> Void) {
    CENNotifications.application(application, handleActionWithIdentifier: identifier, forRemoteNotification: userInfo,
                                 withResponseInfo: responseInfo, completionHandler: completionHandler)
  }
  
  func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse,
                              withCompletionHandler completionHandler: @escaping () -> Void) {
    CENNotifications.userNotificationCenter(center, didReceive: response, withCompletionHandler: completionHandler)
  }
  
  func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification,
                              withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
    CENNotifications.userNotificationCenter(center, willPresent: notification, withCompletionHandler: completionHandler)
  }
  
  // MARK: - Pre-iOS 10 notification delegates
  
  func application(_ application: UIApplication, didRegister notificationSettings: UIUserNotificationSettings) {
    CENNotifications.application(application, didRegister: notificationSettings)
  }
  
}

```

**Bridging-Header.h**

```
//
//  Header.h
// 
//  Created by Alyssa Wolejko on 7/19/18.
//  Copyright © 2018 Facebook. All rights reserved.
//

#ifndef Header_h
#define Header_h

#import <React/RCTBridgeModule.h>
#import <React/RCTBridge.h>
#import <React/RCTEventDispatcher.h>
#import <React/RCTRootView.h>
#import <React/RCTUtils.h>
#import <React/RCTConvert.h>
#import <React/RCTBundleURLProvider.h>

#import <CENNotifications.h>

#endif /* Header_h */

```

**xCode Framework Search Paths**
<img width="781" alt="screen shot 2018-08-06 at 6 25 30 pm" src="https://user-images.githubusercontent.com/8005760/43744063-5a16b8de-99a6-11e8-8cd5-10bfa720c94a.png">

Hope this helps!

**Comment by martinvol** [comment]
Thanks again for the aswer @parfeon

I do not really want to want to have `.swift` files in my project, but as the documentations says that I need to copy code there for the notifications to work.

So if I don't have the `.swift` file I don't need to copy paste code there and it will just work? Do I need to do something else in that case?

Best

**Comment by martinvol** [comment]
Thanks @alyssawolejko for sharing!

**Comment by parfeon** [comment]
@martinvol for @alyssawolejko was different case - they didn't wanted to add another dependency manager into their project and preferred manual plugin code addition (dragging `CENNotifications` folder into Xcode project).  

If your project has been created as Objective-C project (AppDelegate.[hm] files there), then you can copy code from demo application in this repository. 
For Objective-C you need to copy [this](https://github.com/pubnub/chat-engine-push-notifications/blob/master/demo/ios/ChatOnReact/Classes/Controller/CEPNAppDelegate.m#L43-L86) highlighted code and [this](https://github.com/pubnub/chat-engine-push-notifications/blob/master/demo/ios/ChatOnReact/Classes/Controller/CEPNAppDelegate.m#L29) using same locations. Plugin should be imported like [this](https://github.com/pubnub/chat-engine-push-notifications/blob/master/demo/ios/ChatOnReact/Classes/Controller/CEPNAppDelegate.m#L2) in case if you used CocoaPods integration or `#import <CENNotifications.h>` in other case.

**Comment by martinvol** [comment]
It worked! Now I have `ChatEngine.me.notifications` in my env!

I think the documentation should also include this method you explained me.

Best!

**Comment by parfeon** [comment]
@martinvol Good to hear!

If it possible, can you resolve ticket in PubNub support also?

Best regards,
Serhii Mamontov

**Comment by alyssawolejko** [comment]
Hi again @parfeon, 

I'm now experiencing the original issue with Android... https://github.com/pubnub/chat-engine-push-notifications/issues/6#issue-340258048

<img width="698" alt="screen shot 2018-10-22 at 4 16 07 pm" src="https://user-images.githubusercontent.com/8005760/47316799-f05bb780-d615-11e8-82b0-23ba75694780.png">
Could there be another fix needed for the ChatEngine SDK?

**Comment by parfeon** [comment]
Hi @alyssawolejko 

1) Is it happens only for Android?
2) Is there anywhere in Android part of ReactNative application any usage of `async` module?
3) What version of `chat-engine` currently installed into project (actual version is **0.9.19**)?
4) What happened right before this error popped out (what actions has been done with ChatEngine client)?
5) Is there any useful information collapsed in "Possible Unhandled Promise Rejection (id: 0)"?

Plugin itself doesn't use this library, but some of them used in ChatEngine JS library itself.

**Comment by alyssawolejko** [comment]
@parfeon 
This is only happening on Android
I am using chat-engine version 0.9.18
We have some standard `async/await` code but nothing specific for Android.

Here is the output from ChatEngine in debugging mode: 
![screen shot 2018-10-23 at 3 03 50 pm](https://user-images.githubusercontent.com/8005760/47384968-c4ecd180-d6d6-11e8-9811-8524dd7637b2.png)

**Comment by aria6** [comment]
> Hi again @parfeon,
> 
> I'm now experiencing the original issue with Android... [#6 (comment)](https://github.com/pubnub/chat-engine-push-notifications/issues/6#issue-340258048)
> 
> <img alt="screen shot 2018-10-22 at 4 16 07 pm" width="698" src="https://user-images.githubusercontent.com/8005760/47316799-f05bb780-d615-11e8-82b0-23ba75694780.png">
> 
> Could there be another fix needed for the ChatEngine SDK?

I have this issue too 😕

**Comment by parfeon** [comment]
Hi @alyssawolejko thanks for info!

For verification I'm using [this](https://github.com/pubnub/chat-engine-push-notifications/tree/master/demo) demo project which: [register proto-plugin](https://github.com/pubnub/chat-engine-push-notifications/blob/master/demo/index.ios.js#L20-L26), [requests permissions](https://github.com/pubnub/chat-engine-push-notifications/blob/master/demo/src/screens/chats-list.js#L113-L116) and allow to create chat and send message in it. If another device received proper device push token and [PubNub account properly configured with push certificate](https://www.pubnub.com/docs/web-javascript/mobile-gateway#apns-prerequisites-certs) it should receive push notification while application in background.

Two devices (iPad and iPhone) used to verify their ability to communicate with each other with push notifications. With this demo application there was no mentioned issues with callback as shown on screenshot.

Is it possible to compare somehow code of your application and [this](https://github.com/pubnub/chat-engine-push-notifications/tree/master/demo) demo application in part of plugin usage?

What versions of `react` and `react-native` used in your project? [This](https://github.com/pubnub/chat-engine-push-notifications/tree/master/demo) demo application run w/o any troubles with `react: 16.6.0` and `react-native: 0.55.4`.

**Comment by alyssawolejko** [comment]
@parfeon 
Only seeing this issue on Android, is the demo tested & verified for an Android device?
Using `react: 16.3.1` and `react-native: 0.55.4`

The code of my application is in the first message of this thread: https://github.com/pubnub/chat-engine-push-notifications/issues/6#issue-340258048

I am able to connect to ChatEngine on Android without this plugin init code: 
```
ChatEngine.proto(
  'Me',
  plugin({
    events: ['$.invite', 'message'],
    platforms: { ios: true, android: true },
  })
);
```

Other Android info:  
```
    compileSdkVersion 27
    buildToolsVersion '27.0.3'
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:4.1.0'
    }
```

**Comment by parfeon** [comment]
@alyssawolejko 
Sorry, it really took me to long since there was troubles with environment setup on new workstation.

Demo application has been tested at the days, when it has been created. Interface on all platforms has been shown properly on all platforms. Since that moment something has been changed in Android itself or ReactNative (or both) which caused wrong ReactNative view placement (dimensions) in holder view of activity.

Also Firebase deprecated **FirebaseInstanceIdService**, which has been used to track moment, when device receive token for notifications. Because of this change, plugin stopped this information retrieval - because of this it didn't complete automated chats registration process (as they created by user). 

Also dependencies has been updated for module and NodeJS package.

All this changes is pending for their approval in this pull request https://github.com/pubnub/chat-engine-push-notifications/pull/10 and further transition to master.
After demo application has been restored, I wasn't able to get any unhandled promise rejections. Used three devices for tests: iPhone X, iPad mini and Hawei P8 Lite (Android 8.0 Oreo). Tests shown what notification get passed between various devices (properly updated payload for published event to trigger notifications). Also, when opened on one of devices, all other got special notification to remove it from Notification Center.

I will ping you back as soon as it will be moved to NPM repository and ready for tests.

**Comment by nishith-pubnub** [comment]
@parfeon Question from Franklin. "Thank you Sergey - appreciate the response. What is the expected timeline for merging into the npm repo?"

**Comment by parfeon** [comment]
@nishith-pubnub I'm waiting for pull request approve and there will be another one against master with bumped version.

**Comment by nishith-pubnub** [comment]
@alyssawolejko We'll close this channel so all communication can go through PubNub Support. Please continue to monitor progress on this ticket there.
https://support.pubnub.com/a/tickets/10513

**Comment by parfeon** [comment]
@aria6 I don't use `react-native`. I use native tools to build project (Android Studio / IntelliJ IDEA) and Xcode and `react-native` only as deployment server for JS side.

**Comment by aria6** [comment]
Hello @parfeon i has tried to use native tools to build project (Android Studio) but it still shows the same error (for my [project](https://github.com/aria6/chat-engine-push-notification))

And now i'm trying your demo and i got stuck here (it's same error with my project when it does some authorization, but the error doesn't appear on your demo) :

<img width="559" alt="screen shot 2018-12-03 at 5 58 35 pm" src="https://user-images.githubusercontent.com/9672170/49370126-e0abb480-f725-11e8-8397-1b662f11e978.png">

**Comment by parfeon** [comment]
@aria6 as I understand, demo project from plugin repository works? I've used actual device to test demo application.

With your project, I've updated dependencies and Gradle configuration to values which is set in demo project from this repository, before I found actual issue.
Actual issue: incomplete plugin integration on android side according to provided documentation. There is no `CENNotificationsPackage` returned from `getPackages()` function. Please, see 5th paragraph from [this](https://github.com/pubnub/chat-engine-push-notifications/wiki/integration#chat-demo-1) integration actions list.

**Comment by parfeon** [comment]
@alyssawolejko I've been notified, what you still experience this issue.
Recently I was able to debug code provided by @aria6 and appears, what incomplete Android application  configuration has been done. 
Can you please review [my response](https://github.com/pubnub/chat-engine-push-notifications/issues/6#issuecomment-443716444) and check whether it is the same for your application or not (at least error message and line numbers was almost the same for both cases).
